### ISSUE TITLE
Creatures missing from Firefox Bestiary

### ISSUE THREAD

**Issue by glassed** [TheGiddyLimit/TheGiddyLimit.github.io#251] opened 2019-02-14 15:03 UTC
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Certain creatures don't show up in Firefox despite having same default settings as Chrome

Page(s) affected: Bestiary

Reproduction steps: Reset filters to default and search for certain creatures (either in the master list or by name). In Firefox, I've noticed that certain Undead don't come up: (Ghosts, Wraiths, and Banshees, though there could be more). In Chrome they show up just fine.

Additional information:
![screen shot 2019-02-14 at 10 00 59 am](https://user-images.githubusercontent.com/47636194/52795296-7d9c9f00-303f-11e9-9034-51b7db1f8fd9.png)

Browser (Chromium, Firefox, Edge, etc): Firefox 65.0

Platform (Windows, iOS, Android, etc): Both Windows 7 and iOS

**Comment by TheGiddyLimit** [comment] 2019-02-14 15:38
Duplicate of #249 #250

**Closed by TheGiddyLimit** 2019-02-14 15:38 UTC
